# -*- coding: utf-8 -*-
"""API - CHATGPT com Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GAQol4s_DuDzJXazw4rnRVPCIhdcq2Y-
"""

!pip install openai

import openai

# seta a API key

openai.api_key = 'CHAVE SECRETA' # Chave copiada da plataforma OPENAI



openai.ChatCompletion.create(

  model = "gpt-3.5-turbo", #"gpt-4" caso queira usar a versão 4 que é atual, porém mais pesado

  messages=[

        {"role": "system", "content": "Você é um assistente prestativo."} # seta a persona do modelo, se vai ser formal,sarcástico,etc.

  ]



imput_message = imput('Esperando imput: ')

messages.append({"role": "user","content": imput_message}) # adiciona sua pergunta no histórico do chat



#  enquanto o imput não for a palavra 'fim'

while imput_message != 'fim':

  response = openai.ChatCompletion.create(

    model = "gpt-3.5-turbo", #"gpt-4" caso queira usar a versão 4 que é atual, porém mais pesado

    messages = messages,

    temperature = 1,

    max_tokens = 400 #tamanho máximo de letras que poderão ser usadas para responder

 )



 answer = response ['choices'][0]['message']['content']

 messages.append({"role": "assistant", "content": answer})



 #imprime a resposta do chat GPT

 print("Resposta", answer)



 imput_message = imput('Esperando input: ')

 messages.append({"role": "user", "content": input_message}) # adiciona sua pergunta no histórico do chat